// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rectangle.Persistence;

#nullable disable

namespace Rectangle.Persistence.Migrations
{
    [DbContext(typeof(RectangleDbContext))]
    [Migration("20230511194547_index023")]
    partial class index023
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rectangles.Domain.CoordRectangle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LeftX")
                        .HasColumnType("int");

                    b.Property<int>("LeftY")
                        .HasColumnType("int");

                    b.Property<int>("RightX")
                        .HasColumnType("int");

                    b.Property<int>("RightY")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("LeftX", "RightX", "LeftY", "RightY");

                    b.ToTable("Rectangles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LeftX = 21,
                            LeftY = -98,
                            RightX = 55,
                            RightY = -124
                        },
                        new
                        {
                            Id = 2,
                            LeftX = -14,
                            LeftY = -12,
                            RightX = 67,
                            RightY = -64
                        },
                        new
                        {
                            Id = 3,
                            LeftX = 32,
                            LeftY = 29,
                            RightX = 69,
                            RightY = -8
                        },
                        new
                        {
                            Id = 4,
                            LeftX = 89,
                            LeftY = 70,
                            RightX = 183,
                            RightY = 22
                        },
                        new
                        {
                            Id = 5,
                            LeftX = -80,
                            LeftY = 70,
                            RightX = -34,
                            RightY = 9
                        },
                        new
                        {
                            Id = 6,
                            LeftX = -2,
                            LeftY = 35,
                            RightX = 46,
                            RightY = -54
                        },
                        new
                        {
                            Id = 7,
                            LeftX = 45,
                            LeftY = 77,
                            RightX = 57,
                            RightY = 20
                        },
                        new
                        {
                            Id = 8,
                            LeftX = -29,
                            LeftY = 1,
                            RightX = 42,
                            RightY = -89
                        },
                        new
                        {
                            Id = 9,
                            LeftX = 64,
                            LeftY = 4,
                            RightX = 128,
                            RightY = -38
                        },
                        new
                        {
                            Id = 10,
                            LeftX = -68,
                            LeftY = 48,
                            RightX = 1,
                            RightY = 21
                        },
                        new
                        {
                            Id = 11,
                            LeftX = -3,
                            LeftY = 17,
                            RightX = 91,
                            RightY = -9
                        },
                        new
                        {
                            Id = 12,
                            LeftX = 29,
                            LeftY = 25,
                            RightX = 40,
                            RightY = 19
                        },
                        new
                        {
                            Id = 13,
                            LeftX = -49,
                            LeftY = -22,
                            RightX = -42,
                            RightY = -96
                        },
                        new
                        {
                            Id = 14,
                            LeftX = -65,
                            LeftY = -9,
                            RightX = -11,
                            RightY = -63
                        },
                        new
                        {
                            Id = 15,
                            LeftX = 47,
                            LeftY = 84,
                            RightX = 53,
                            RightY = -1
                        },
                        new
                        {
                            Id = 16,
                            LeftX = -40,
                            LeftY = -87,
                            RightX = 43,
                            RightY = -93
                        },
                        new
                        {
                            Id = 17,
                            LeftX = -74,
                            LeftY = -81,
                            RightX = -22,
                            RightY = -99
                        },
                        new
                        {
                            Id = 18,
                            LeftX = -9,
                            LeftY = 91,
                            RightX = 6,
                            RightY = 27
                        },
                        new
                        {
                            Id = 19,
                            LeftX = -90,
                            LeftY = -92,
                            RightX = 4,
                            RightY = -98
                        },
                        new
                        {
                            Id = 20,
                            LeftX = -27,
                            LeftY = -23,
                            RightX = 31,
                            RightY = -109
                        },
                        new
                        {
                            Id = 21,
                            LeftX = 17,
                            LeftY = 67,
                            RightX = 88,
                            RightY = -24
                        },
                        new
                        {
                            Id = 22,
                            LeftX = -8,
                            LeftY = 26,
                            RightX = 47,
                            RightY = -44
                        },
                        new
                        {
                            Id = 23,
                            LeftX = -2,
                            LeftY = -15,
                            RightX = 35,
                            RightY = -73
                        },
                        new
                        {
                            Id = 24,
                            LeftX = 93,
                            LeftY = -100,
                            RightX = 147,
                            RightY = -133
                        },
                        new
                        {
                            Id = 25,
                            LeftX = 3,
                            LeftY = 30,
                            RightX = 24,
                            RightY = -1
                        },
                        new
                        {
                            Id = 26,
                            LeftX = 64,
                            LeftY = 65,
                            RightX = 68,
                            RightY = -30
                        },
                        new
                        {
                            Id = 27,
                            LeftX = -27,
                            LeftY = -77,
                            RightX = -12,
                            RightY = -171
                        },
                        new
                        {
                            Id = 28,
                            LeftX = 44,
                            LeftY = -69,
                            RightX = 96,
                            RightY = -163
                        },
                        new
                        {
                            Id = 29,
                            LeftX = 96,
                            LeftY = 42,
                            RightX = 170,
                            RightY = -2
                        },
                        new
                        {
                            Id = 30,
                            LeftX = 53,
                            LeftY = 26,
                            RightX = 109,
                            RightY = -24
                        },
                        new
                        {
                            Id = 31,
                            LeftX = 85,
                            LeftY = 27,
                            RightX = 151,
                            RightY = -64
                        },
                        new
                        {
                            Id = 32,
                            LeftX = 33,
                            LeftY = 94,
                            RightX = 92,
                            RightY = 43
                        },
                        new
                        {
                            Id = 33,
                            LeftX = 2,
                            LeftY = 53,
                            RightX = 83,
                            RightY = -45
                        },
                        new
                        {
                            Id = 34,
                            LeftX = 21,
                            LeftY = -82,
                            RightX = 22,
                            RightY = -89
                        },
                        new
                        {
                            Id = 35,
                            LeftX = 15,
                            LeftY = -25,
                            RightX = 72,
                            RightY = -98
                        },
                        new
                        {
                            Id = 36,
                            LeftX = 50,
                            LeftY = 12,
                            RightX = 73,
                            RightY = -60
                        },
                        new
                        {
                            Id = 37,
                            LeftX = -3,
                            LeftY = -90,
                            RightX = 69,
                            RightY = -174
                        },
                        new
                        {
                            Id = 38,
                            LeftX = 86,
                            LeftY = -59,
                            RightX = 137,
                            RightY = -133
                        },
                        new
                        {
                            Id = 39,
                            LeftX = -72,
                            LeftY = 6,
                            RightX = -53,
                            RightY = -69
                        },
                        new
                        {
                            Id = 40,
                            LeftX = 51,
                            LeftY = 31,
                            RightX = 104,
                            RightY = -10
                        },
                        new
                        {
                            Id = 41,
                            LeftX = -58,
                            LeftY = -39,
                            RightX = -47,
                            RightY = -88
                        },
                        new
                        {
                            Id = 42,
                            LeftX = -53,
                            LeftY = 66,
                            RightX = -1,
                            RightY = -4
                        },
                        new
                        {
                            Id = 43,
                            LeftX = -78,
                            LeftY = -86,
                            RightX = 8,
                            RightY = -114
                        },
                        new
                        {
                            Id = 44,
                            LeftX = 52,
                            LeftY = -84,
                            RightX = 102,
                            RightY = -183
                        },
                        new
                        {
                            Id = 45,
                            LeftX = -85,
                            LeftY = 9,
                            RightX = -64,
                            RightY = -16
                        },
                        new
                        {
                            Id = 46,
                            LeftX = 88,
                            LeftY = 36,
                            RightX = 152,
                            RightY = 29
                        },
                        new
                        {
                            Id = 47,
                            LeftX = -15,
                            LeftY = 79,
                            RightX = 25,
                            RightY = 36
                        },
                        new
                        {
                            Id = 48,
                            LeftX = 46,
                            LeftY = -79,
                            RightX = 139,
                            RightY = -121
                        },
                        new
                        {
                            Id = 49,
                            LeftX = 54,
                            LeftY = -2,
                            RightX = 76,
                            RightY = -30
                        },
                        new
                        {
                            Id = 50,
                            LeftX = -96,
                            LeftY = -82,
                            RightX = -63,
                            RightY = -162
                        },
                        new
                        {
                            Id = 51,
                            LeftX = -27,
                            LeftY = 63,
                            RightX = 20,
                            RightY = -2
                        },
                        new
                        {
                            Id = 52,
                            LeftX = -42,
                            LeftY = 71,
                            RightX = -9,
                            RightY = 67
                        },
                        new
                        {
                            Id = 53,
                            LeftX = 33,
                            LeftY = -51,
                            RightX = 104,
                            RightY = -150
                        },
                        new
                        {
                            Id = 54,
                            LeftX = 43,
                            LeftY = 12,
                            RightX = 49,
                            RightY = -36
                        },
                        new
                        {
                            Id = 55,
                            LeftX = 18,
                            LeftY = -2,
                            RightX = 43,
                            RightY = -8
                        },
                        new
                        {
                            Id = 56,
                            LeftX = 68,
                            LeftY = 11,
                            RightX = 156,
                            RightY = 2
                        },
                        new
                        {
                            Id = 57,
                            LeftX = 82,
                            LeftY = -19,
                            RightX = 110,
                            RightY = -64
                        },
                        new
                        {
                            Id = 58,
                            LeftX = 5,
                            LeftY = 23,
                            RightX = 53,
                            RightY = -22
                        },
                        new
                        {
                            Id = 59,
                            LeftX = 24,
                            LeftY = 97,
                            RightX = 65,
                            RightY = 64
                        },
                        new
                        {
                            Id = 60,
                            LeftX = 6,
                            LeftY = 3,
                            RightX = 65,
                            RightY = -43
                        },
                        new
                        {
                            Id = 61,
                            LeftX = 13,
                            LeftY = 62,
                            RightX = 41,
                            RightY = 15
                        },
                        new
                        {
                            Id = 62,
                            LeftX = 72,
                            LeftY = 93,
                            RightX = 143,
                            RightY = 84
                        },
                        new
                        {
                            Id = 63,
                            LeftX = 83,
                            LeftY = -89,
                            RightX = 104,
                            RightY = -108
                        },
                        new
                        {
                            Id = 64,
                            LeftX = 1,
                            LeftY = 76,
                            RightX = 38,
                            RightY = 29
                        },
                        new
                        {
                            Id = 65,
                            LeftX = 60,
                            LeftY = -52,
                            RightX = 82,
                            RightY = -123
                        },
                        new
                        {
                            Id = 66,
                            LeftX = 29,
                            LeftY = 15,
                            RightX = 74,
                            RightY = -80
                        },
                        new
                        {
                            Id = 67,
                            LeftX = 78,
                            LeftY = -44,
                            RightX = 165,
                            RightY = -56
                        },
                        new
                        {
                            Id = 68,
                            LeftX = 21,
                            LeftY = -14,
                            RightX = 101,
                            RightY = -15
                        },
                        new
                        {
                            Id = 69,
                            LeftX = -48,
                            LeftY = -87,
                            RightX = 0,
                            RightY = -127
                        },
                        new
                        {
                            Id = 70,
                            LeftX = -2,
                            LeftY = -56,
                            RightX = 74,
                            RightY = -69
                        },
                        new
                        {
                            Id = 71,
                            LeftX = -64,
                            LeftY = 29,
                            RightX = -37,
                            RightY = 20
                        },
                        new
                        {
                            Id = 72,
                            LeftX = -88,
                            LeftY = 2,
                            RightX = -58,
                            RightY = -53
                        },
                        new
                        {
                            Id = 73,
                            LeftX = -82,
                            LeftY = -62,
                            RightX = -79,
                            RightY = -132
                        },
                        new
                        {
                            Id = 74,
                            LeftX = -50,
                            LeftY = 27,
                            RightX = 38,
                            RightY = -26
                        },
                        new
                        {
                            Id = 75,
                            LeftX = -68,
                            LeftY = 85,
                            RightX = 12,
                            RightY = 70
                        },
                        new
                        {
                            Id = 76,
                            LeftX = -20,
                            LeftY = 99,
                            RightX = 60,
                            RightY = 71
                        },
                        new
                        {
                            Id = 77,
                            LeftX = -1,
                            LeftY = 78,
                            RightX = 81,
                            RightY = 3
                        },
                        new
                        {
                            Id = 78,
                            LeftX = 78,
                            LeftY = 40,
                            RightX = 141,
                            RightY = 9
                        },
                        new
                        {
                            Id = 79,
                            LeftX = 55,
                            LeftY = -20,
                            RightX = 65,
                            RightY = -64
                        },
                        new
                        {
                            Id = 80,
                            LeftX = -83,
                            LeftY = 13,
                            RightX = -61,
                            RightY = -21
                        },
                        new
                        {
                            Id = 81,
                            LeftX = 59,
                            LeftY = 16,
                            RightX = 85,
                            RightY = -32
                        },
                        new
                        {
                            Id = 82,
                            LeftX = -80,
                            LeftY = 7,
                            RightX = -11,
                            RightY = -40
                        },
                        new
                        {
                            Id = 83,
                            LeftX = 13,
                            LeftY = 45,
                            RightX = 51,
                            RightY = 16
                        },
                        new
                        {
                            Id = 84,
                            LeftX = 40,
                            LeftY = -85,
                            RightX = 101,
                            RightY = -141
                        },
                        new
                        {
                            Id = 85,
                            LeftX = -100,
                            LeftY = -73,
                            RightX = -5,
                            RightY = -117
                        },
                        new
                        {
                            Id = 86,
                            LeftX = 87,
                            LeftY = 94,
                            RightX = 121,
                            RightY = 29
                        },
                        new
                        {
                            Id = 87,
                            LeftX = -38,
                            LeftY = 3,
                            RightX = 52,
                            RightY = -30
                        },
                        new
                        {
                            Id = 88,
                            LeftX = 99,
                            LeftY = 52,
                            RightX = 125,
                            RightY = 23
                        },
                        new
                        {
                            Id = 89,
                            LeftX = 28,
                            LeftY = 83,
                            RightX = 44,
                            RightY = 34
                        },
                        new
                        {
                            Id = 90,
                            LeftX = 70,
                            LeftY = -18,
                            RightX = 116,
                            RightY = -26
                        },
                        new
                        {
                            Id = 91,
                            LeftX = -9,
                            LeftY = -50,
                            RightX = 42,
                            RightY = -55
                        },
                        new
                        {
                            Id = 92,
                            LeftX = 99,
                            LeftY = -38,
                            RightX = 160,
                            RightY = -43
                        },
                        new
                        {
                            Id = 93,
                            LeftX = 2,
                            LeftY = -87,
                            RightX = 101,
                            RightY = -118
                        },
                        new
                        {
                            Id = 94,
                            LeftX = 86,
                            LeftY = 42,
                            RightX = 166,
                            RightY = -49
                        },
                        new
                        {
                            Id = 95,
                            LeftX = 4,
                            LeftY = -87,
                            RightX = 55,
                            RightY = -176
                        },
                        new
                        {
                            Id = 96,
                            LeftX = 75,
                            LeftY = -2,
                            RightX = 86,
                            RightY = -72
                        },
                        new
                        {
                            Id = 97,
                            LeftX = -90,
                            LeftY = 86,
                            RightX = -63,
                            RightY = -7
                        },
                        new
                        {
                            Id = 98,
                            LeftX = -92,
                            LeftY = -10,
                            RightX = -68,
                            RightY = -90
                        },
                        new
                        {
                            Id = 99,
                            LeftX = -2,
                            LeftY = -67,
                            RightX = 73,
                            RightY = -132
                        },
                        new
                        {
                            Id = 100,
                            LeftX = 1,
                            LeftY = -14,
                            RightX = 45,
                            RightY = -18
                        },
                        new
                        {
                            Id = 101,
                            LeftX = 26,
                            LeftY = -79,
                            RightX = 68,
                            RightY = -127
                        },
                        new
                        {
                            Id = 102,
                            LeftX = -44,
                            LeftY = 0,
                            RightX = -1,
                            RightY = -28
                        },
                        new
                        {
                            Id = 103,
                            LeftX = 79,
                            LeftY = 29,
                            RightX = 84,
                            RightY = -33
                        },
                        new
                        {
                            Id = 104,
                            LeftX = -9,
                            LeftY = 40,
                            RightX = 36,
                            RightY = -48
                        },
                        new
                        {
                            Id = 105,
                            LeftX = -84,
                            LeftY = 40,
                            RightX = -32,
                            RightY = -51
                        },
                        new
                        {
                            Id = 106,
                            LeftX = -95,
                            LeftY = 34,
                            RightX = -84,
                            RightY = 19
                        },
                        new
                        {
                            Id = 107,
                            LeftX = 64,
                            LeftY = -94,
                            RightX = 79,
                            RightY = -123
                        },
                        new
                        {
                            Id = 108,
                            LeftX = 16,
                            LeftY = -92,
                            RightX = 75,
                            RightY = -117
                        },
                        new
                        {
                            Id = 109,
                            LeftX = 10,
                            LeftY = 27,
                            RightX = 108,
                            RightY = -69
                        },
                        new
                        {
                            Id = 110,
                            LeftX = -19,
                            LeftY = -61,
                            RightX = 46,
                            RightY = -73
                        },
                        new
                        {
                            Id = 111,
                            LeftX = 36,
                            LeftY = 92,
                            RightX = 99,
                            RightY = 13
                        },
                        new
                        {
                            Id = 112,
                            LeftX = 16,
                            LeftY = 26,
                            RightX = 100,
                            RightY = -4
                        },
                        new
                        {
                            Id = 113,
                            LeftX = -73,
                            LeftY = 9,
                            RightX = -54,
                            RightY = -47
                        },
                        new
                        {
                            Id = 114,
                            LeftX = 42,
                            LeftY = 89,
                            RightX = 83,
                            RightY = 59
                        },
                        new
                        {
                            Id = 115,
                            LeftX = 56,
                            LeftY = -21,
                            RightX = 95,
                            RightY = -52
                        },
                        new
                        {
                            Id = 116,
                            LeftX = 37,
                            LeftY = -27,
                            RightX = 102,
                            RightY = -121
                        },
                        new
                        {
                            Id = 117,
                            LeftX = 13,
                            LeftY = -39,
                            RightX = 104,
                            RightY = -52
                        },
                        new
                        {
                            Id = 118,
                            LeftX = 83,
                            LeftY = -13,
                            RightX = 176,
                            RightY = -70
                        },
                        new
                        {
                            Id = 119,
                            LeftX = 40,
                            LeftY = -85,
                            RightX = 98,
                            RightY = -135
                        },
                        new
                        {
                            Id = 120,
                            LeftX = -46,
                            LeftY = 78,
                            RightX = 40,
                            RightY = -4
                        },
                        new
                        {
                            Id = 121,
                            LeftX = -42,
                            LeftY = -93,
                            RightX = 5,
                            RightY = -145
                        },
                        new
                        {
                            Id = 122,
                            LeftX = -66,
                            LeftY = -56,
                            RightX = 31,
                            RightY = -143
                        },
                        new
                        {
                            Id = 123,
                            LeftX = -16,
                            LeftY = 36,
                            RightX = 66,
                            RightY = -39
                        },
                        new
                        {
                            Id = 124,
                            LeftX = 55,
                            LeftY = -83,
                            RightX = 148,
                            RightY = -164
                        },
                        new
                        {
                            Id = 125,
                            LeftX = -62,
                            LeftY = 92,
                            RightX = -37,
                            RightY = 4
                        },
                        new
                        {
                            Id = 126,
                            LeftX = 19,
                            LeftY = -97,
                            RightX = 108,
                            RightY = -169
                        },
                        new
                        {
                            Id = 127,
                            LeftX = 46,
                            LeftY = 4,
                            RightX = 97,
                            RightY = -18
                        },
                        new
                        {
                            Id = 128,
                            LeftX = 36,
                            LeftY = 54,
                            RightX = 51,
                            RightY = -30
                        },
                        new
                        {
                            Id = 129,
                            LeftX = 70,
                            LeftY = -38,
                            RightX = 87,
                            RightY = -131
                        },
                        new
                        {
                            Id = 130,
                            LeftX = -96,
                            LeftY = 45,
                            RightX = -75,
                            RightY = 24
                        },
                        new
                        {
                            Id = 131,
                            LeftX = -54,
                            LeftY = -90,
                            RightX = 40,
                            RightY = -165
                        },
                        new
                        {
                            Id = 132,
                            LeftX = 74,
                            LeftY = -91,
                            RightX = 111,
                            RightY = -162
                        },
                        new
                        {
                            Id = 133,
                            LeftX = 40,
                            LeftY = 97,
                            RightX = 92,
                            RightY = 26
                        },
                        new
                        {
                            Id = 134,
                            LeftX = -14,
                            LeftY = -93,
                            RightX = -10,
                            RightY = -185
                        },
                        new
                        {
                            Id = 135,
                            LeftX = -3,
                            LeftY = -51,
                            RightX = 29,
                            RightY = -87
                        },
                        new
                        {
                            Id = 136,
                            LeftX = -71,
                            LeftY = 94,
                            RightX = 26,
                            RightY = 67
                        },
                        new
                        {
                            Id = 137,
                            LeftX = 83,
                            LeftY = 38,
                            RightX = 177,
                            RightY = -1
                        },
                        new
                        {
                            Id = 138,
                            LeftX = -2,
                            LeftY = -4,
                            RightX = 52,
                            RightY = -75
                        },
                        new
                        {
                            Id = 139,
                            LeftX = -58,
                            LeftY = -11,
                            RightX = -38,
                            RightY = -56
                        },
                        new
                        {
                            Id = 140,
                            LeftX = -66,
                            LeftY = 46,
                            RightX = -33,
                            RightY = -16
                        },
                        new
                        {
                            Id = 141,
                            LeftX = -64,
                            LeftY = 70,
                            RightX = 28,
                            RightY = 11
                        },
                        new
                        {
                            Id = 142,
                            LeftX = 68,
                            LeftY = -33,
                            RightX = 121,
                            RightY = -47
                        },
                        new
                        {
                            Id = 143,
                            LeftX = -19,
                            LeftY = -59,
                            RightX = 35,
                            RightY = -101
                        },
                        new
                        {
                            Id = 144,
                            LeftX = 13,
                            LeftY = 10,
                            RightX = 87,
                            RightY = -16
                        },
                        new
                        {
                            Id = 145,
                            LeftX = -13,
                            LeftY = 76,
                            RightX = 73,
                            RightY = 30
                        },
                        new
                        {
                            Id = 146,
                            LeftX = 90,
                            LeftY = -28,
                            RightX = 164,
                            RightY = -42
                        },
                        new
                        {
                            Id = 147,
                            LeftX = 42,
                            LeftY = 8,
                            RightX = 138,
                            RightY = -89
                        },
                        new
                        {
                            Id = 148,
                            LeftX = -10,
                            LeftY = -88,
                            RightX = 86,
                            RightY = -170
                        },
                        new
                        {
                            Id = 149,
                            LeftX = 49,
                            LeftY = 23,
                            RightX = 105,
                            RightY = -60
                        },
                        new
                        {
                            Id = 150,
                            LeftX = 51,
                            LeftY = 74,
                            RightX = 69,
                            RightY = 21
                        },
                        new
                        {
                            Id = 151,
                            LeftX = -17,
                            LeftY = 62,
                            RightX = 35,
                            RightY = -22
                        },
                        new
                        {
                            Id = 152,
                            LeftX = 4,
                            LeftY = -52,
                            RightX = 32,
                            RightY = -72
                        },
                        new
                        {
                            Id = 153,
                            LeftX = -27,
                            LeftY = 82,
                            RightX = 36,
                            RightY = -14
                        },
                        new
                        {
                            Id = 154,
                            LeftX = 97,
                            LeftY = 76,
                            RightX = 184,
                            RightY = 51
                        },
                        new
                        {
                            Id = 155,
                            LeftX = 36,
                            LeftY = -47,
                            RightX = 62,
                            RightY = -119
                        },
                        new
                        {
                            Id = 156,
                            LeftX = 72,
                            LeftY = 22,
                            RightX = 87,
                            RightY = -48
                        },
                        new
                        {
                            Id = 157,
                            LeftX = 61,
                            LeftY = 62,
                            RightX = 124,
                            RightY = 35
                        },
                        new
                        {
                            Id = 158,
                            LeftX = 23,
                            LeftY = -30,
                            RightX = 102,
                            RightY = -111
                        },
                        new
                        {
                            Id = 159,
                            LeftX = 80,
                            LeftY = 46,
                            RightX = 140,
                            RightY = 16
                        },
                        new
                        {
                            Id = 160,
                            LeftX = 22,
                            LeftY = 99,
                            RightX = 37,
                            RightY = 74
                        },
                        new
                        {
                            Id = 161,
                            LeftX = -68,
                            LeftY = -72,
                            RightX = -53,
                            RightY = -94
                        },
                        new
                        {
                            Id = 162,
                            LeftX = -64,
                            LeftY = -22,
                            RightX = -1,
                            RightY = -119
                        },
                        new
                        {
                            Id = 163,
                            LeftX = -78,
                            LeftY = -10,
                            RightX = -76,
                            RightY = -65
                        },
                        new
                        {
                            Id = 164,
                            LeftX = -46,
                            LeftY = -68,
                            RightX = -26,
                            RightY = -132
                        },
                        new
                        {
                            Id = 165,
                            LeftX = -11,
                            LeftY = -17,
                            RightX = 1,
                            RightY = -108
                        },
                        new
                        {
                            Id = 166,
                            LeftX = -87,
                            LeftY = 95,
                            RightX = -16,
                            RightY = 20
                        },
                        new
                        {
                            Id = 167,
                            LeftX = 58,
                            LeftY = -20,
                            RightX = 64,
                            RightY = -55
                        },
                        new
                        {
                            Id = 168,
                            LeftX = 81,
                            LeftY = 14,
                            RightX = 84,
                            RightY = -64
                        },
                        new
                        {
                            Id = 169,
                            LeftX = -25,
                            LeftY = 85,
                            RightX = -12,
                            RightY = 45
                        },
                        new
                        {
                            Id = 170,
                            LeftX = 82,
                            LeftY = -89,
                            RightX = 130,
                            RightY = -178
                        },
                        new
                        {
                            Id = 171,
                            LeftX = 17,
                            LeftY = 82,
                            RightX = 106,
                            RightY = 69
                        },
                        new
                        {
                            Id = 172,
                            LeftX = 28,
                            LeftY = -16,
                            RightX = 126,
                            RightY = -88
                        },
                        new
                        {
                            Id = 173,
                            LeftX = -28,
                            LeftY = 91,
                            RightX = -21,
                            RightY = 6
                        },
                        new
                        {
                            Id = 174,
                            LeftX = 86,
                            LeftY = 75,
                            RightX = 134,
                            RightY = -22
                        },
                        new
                        {
                            Id = 175,
                            LeftX = 44,
                            LeftY = -83,
                            RightX = 138,
                            RightY = -104
                        },
                        new
                        {
                            Id = 176,
                            LeftX = 52,
                            LeftY = 47,
                            RightX = 130,
                            RightY = 40
                        },
                        new
                        {
                            Id = 177,
                            LeftX = -26,
                            LeftY = -28,
                            RightX = 58,
                            RightY = -30
                        },
                        new
                        {
                            Id = 178,
                            LeftX = 25,
                            LeftY = -29,
                            RightX = 120,
                            RightY = -57
                        },
                        new
                        {
                            Id = 179,
                            LeftX = 88,
                            LeftY = 28,
                            RightX = 138,
                            RightY = -23
                        },
                        new
                        {
                            Id = 180,
                            LeftX = 36,
                            LeftY = -71,
                            RightX = 78,
                            RightY = -136
                        },
                        new
                        {
                            Id = 181,
                            LeftX = -49,
                            LeftY = -11,
                            RightX = -37,
                            RightY = -32
                        },
                        new
                        {
                            Id = 182,
                            LeftX = 87,
                            LeftY = 18,
                            RightX = 184,
                            RightY = -13
                        },
                        new
                        {
                            Id = 183,
                            LeftX = 23,
                            LeftY = 6,
                            RightX = 120,
                            RightY = -71
                        },
                        new
                        {
                            Id = 184,
                            LeftX = -5,
                            LeftY = 34,
                            RightX = 89,
                            RightY = 15
                        },
                        new
                        {
                            Id = 185,
                            LeftX = -31,
                            LeftY = -8,
                            RightX = 18,
                            RightY = -34
                        },
                        new
                        {
                            Id = 186,
                            LeftX = 86,
                            LeftY = 16,
                            RightX = 139,
                            RightY = -24
                        },
                        new
                        {
                            Id = 187,
                            LeftX = 74,
                            LeftY = 84,
                            RightX = 98,
                            RightY = 44
                        },
                        new
                        {
                            Id = 188,
                            LeftX = 57,
                            LeftY = 58,
                            RightX = 78,
                            RightY = -15
                        },
                        new
                        {
                            Id = 189,
                            LeftX = 25,
                            LeftY = -34,
                            RightX = 92,
                            RightY = -87
                        },
                        new
                        {
                            Id = 190,
                            LeftX = -99,
                            LeftY = -10,
                            RightX = -90,
                            RightY = -56
                        },
                        new
                        {
                            Id = 191,
                            LeftX = 45,
                            LeftY = 42,
                            RightX = 140,
                            RightY = 10
                        },
                        new
                        {
                            Id = 192,
                            LeftX = 99,
                            LeftY = 1,
                            RightX = 124,
                            RightY = -15
                        },
                        new
                        {
                            Id = 193,
                            LeftX = 56,
                            LeftY = -40,
                            RightX = 65,
                            RightY = -91
                        },
                        new
                        {
                            Id = 194,
                            LeftX = 66,
                            LeftY = 22,
                            RightX = 124,
                            RightY = -14
                        },
                        new
                        {
                            Id = 195,
                            LeftX = 84,
                            LeftY = 71,
                            RightX = 166,
                            RightY = -5
                        },
                        new
                        {
                            Id = 196,
                            LeftX = -83,
                            LeftY = 60,
                            RightX = 7,
                            RightY = -16
                        },
                        new
                        {
                            Id = 197,
                            LeftX = -48,
                            LeftY = 91,
                            RightX = -37,
                            RightY = 87
                        },
                        new
                        {
                            Id = 198,
                            LeftX = -79,
                            LeftY = 79,
                            RightX = -42,
                            RightY = 71
                        },
                        new
                        {
                            Id = 199,
                            LeftX = 75,
                            LeftY = 24,
                            RightX = 116,
                            RightY = -27
                        },
                        new
                        {
                            Id = 200,
                            LeftX = -17,
                            LeftY = 71,
                            RightX = 73,
                            RightY = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
