// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rectangle.Persistence;

#nullable disable

namespace Rectangle.Persistence.Migrations
{
    [DbContext(typeof(RectangleDbContext))]
    [Migration("20230512194535_tt2")]
    partial class tt2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Rectangles.Domain.CoordRectangle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("LeftX")
                        .HasColumnType("int");

                    b.Property<int>("LeftY")
                        .HasColumnType("int");

                    b.Property<int>("RightX")
                        .HasColumnType("int");

                    b.Property<int>("RightY")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("LeftX", "RightX", "LeftY", "RightY");

                    b.ToTable("Rectangles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LeftX = 67,
                            LeftY = 28,
                            RightX = 136,
                            RightY = -12
                        },
                        new
                        {
                            Id = 2,
                            LeftX = -15,
                            LeftY = -2,
                            RightX = 17,
                            RightY = -81
                        },
                        new
                        {
                            Id = 3,
                            LeftX = -34,
                            LeftY = -25,
                            RightX = 17,
                            RightY = -55
                        },
                        new
                        {
                            Id = 4,
                            LeftX = -60,
                            LeftY = -49,
                            RightX = -49,
                            RightY = -64
                        },
                        new
                        {
                            Id = 5,
                            LeftX = 52,
                            LeftY = -72,
                            RightX = 124,
                            RightY = -97
                        },
                        new
                        {
                            Id = 6,
                            LeftX = -82,
                            LeftY = 78,
                            RightX = -76,
                            RightY = 64
                        },
                        new
                        {
                            Id = 7,
                            LeftX = 49,
                            LeftY = -83,
                            RightX = 119,
                            RightY = -167
                        },
                        new
                        {
                            Id = 8,
                            LeftX = -39,
                            LeftY = 23,
                            RightX = 1,
                            RightY = -56
                        },
                        new
                        {
                            Id = 9,
                            LeftX = 35,
                            LeftY = -24,
                            RightX = 78,
                            RightY = -85
                        },
                        new
                        {
                            Id = 10,
                            LeftX = 0,
                            LeftY = -37,
                            RightX = 59,
                            RightY = -49
                        },
                        new
                        {
                            Id = 11,
                            LeftX = 81,
                            LeftY = -27,
                            RightX = 94,
                            RightY = -54
                        },
                        new
                        {
                            Id = 12,
                            LeftX = 83,
                            LeftY = 42,
                            RightX = 175,
                            RightY = 25
                        },
                        new
                        {
                            Id = 13,
                            LeftX = -66,
                            LeftY = 50,
                            RightX = 10,
                            RightY = -1
                        },
                        new
                        {
                            Id = 14,
                            LeftX = -44,
                            LeftY = 39,
                            RightX = 45,
                            RightY = -4
                        },
                        new
                        {
                            Id = 15,
                            LeftX = 60,
                            LeftY = 37,
                            RightX = 158,
                            RightY = -22
                        },
                        new
                        {
                            Id = 16,
                            LeftX = 69,
                            LeftY = 51,
                            RightX = 107,
                            RightY = 30
                        },
                        new
                        {
                            Id = 17,
                            LeftX = 5,
                            LeftY = 24,
                            RightX = 93,
                            RightY = -5
                        },
                        new
                        {
                            Id = 18,
                            LeftX = -12,
                            LeftY = -48,
                            RightX = 7,
                            RightY = -57
                        },
                        new
                        {
                            Id = 19,
                            LeftX = 48,
                            LeftY = 0,
                            RightX = 104,
                            RightY = -4
                        },
                        new
                        {
                            Id = 20,
                            LeftX = 91,
                            LeftY = -53,
                            RightX = 121,
                            RightY = -138
                        },
                        new
                        {
                            Id = 21,
                            LeftX = 10,
                            LeftY = -74,
                            RightX = 23,
                            RightY = -113
                        },
                        new
                        {
                            Id = 22,
                            LeftX = -98,
                            LeftY = 68,
                            RightX = -81,
                            RightY = 32
                        },
                        new
                        {
                            Id = 23,
                            LeftX = -1,
                            LeftY = -54,
                            RightX = 36,
                            RightY = -150
                        },
                        new
                        {
                            Id = 24,
                            LeftX = 24,
                            LeftY = -82,
                            RightX = 46,
                            RightY = -152
                        },
                        new
                        {
                            Id = 25,
                            LeftX = 52,
                            LeftY = 54,
                            RightX = 133,
                            RightY = 48
                        },
                        new
                        {
                            Id = 26,
                            LeftX = -90,
                            LeftY = -29,
                            RightX = -26,
                            RightY = -40
                        },
                        new
                        {
                            Id = 27,
                            LeftX = -35,
                            LeftY = -94,
                            RightX = 30,
                            RightY = -115
                        },
                        new
                        {
                            Id = 28,
                            LeftX = 44,
                            LeftY = -40,
                            RightX = 129,
                            RightY = -83
                        },
                        new
                        {
                            Id = 29,
                            LeftX = -17,
                            LeftY = 86,
                            RightX = -7,
                            RightY = 71
                        },
                        new
                        {
                            Id = 30,
                            LeftX = -90,
                            LeftY = -75,
                            RightX = -43,
                            RightY = -85
                        },
                        new
                        {
                            Id = 31,
                            LeftX = 16,
                            LeftY = -8,
                            RightX = 62,
                            RightY = -31
                        },
                        new
                        {
                            Id = 32,
                            LeftX = -85,
                            LeftY = -41,
                            RightX = 8,
                            RightY = -132
                        },
                        new
                        {
                            Id = 33,
                            LeftX = 36,
                            LeftY = -31,
                            RightX = 100,
                            RightY = -90
                        },
                        new
                        {
                            Id = 34,
                            LeftX = 90,
                            LeftY = -1,
                            RightX = 99,
                            RightY = -91
                        },
                        new
                        {
                            Id = 35,
                            LeftX = 99,
                            LeftY = -19,
                            RightX = 172,
                            RightY = -118
                        },
                        new
                        {
                            Id = 36,
                            LeftX = 19,
                            LeftY = -5,
                            RightX = 79,
                            RightY = -11
                        },
                        new
                        {
                            Id = 37,
                            LeftX = 65,
                            LeftY = 47,
                            RightX = 132,
                            RightY = 39
                        },
                        new
                        {
                            Id = 38,
                            LeftX = 48,
                            LeftY = -6,
                            RightX = 94,
                            RightY = -66
                        },
                        new
                        {
                            Id = 39,
                            LeftX = -61,
                            LeftY = 18,
                            RightX = 5,
                            RightY = -27
                        },
                        new
                        {
                            Id = 40,
                            LeftX = 64,
                            LeftY = 90,
                            RightX = 126,
                            RightY = 61
                        },
                        new
                        {
                            Id = 41,
                            LeftX = -15,
                            LeftY = 80,
                            RightX = 63,
                            RightY = 26
                        },
                        new
                        {
                            Id = 42,
                            LeftX = -35,
                            LeftY = -3,
                            RightX = 0,
                            RightY = -50
                        },
                        new
                        {
                            Id = 43,
                            LeftX = 78,
                            LeftY = -71,
                            RightX = 159,
                            RightY = -104
                        },
                        new
                        {
                            Id = 44,
                            LeftX = -64,
                            LeftY = -95,
                            RightX = -55,
                            RightY = -136
                        },
                        new
                        {
                            Id = 45,
                            LeftX = 49,
                            LeftY = -49,
                            RightX = 83,
                            RightY = -119
                        },
                        new
                        {
                            Id = 46,
                            LeftX = -90,
                            LeftY = -40,
                            RightX = -89,
                            RightY = -99
                        },
                        new
                        {
                            Id = 47,
                            LeftX = -64,
                            LeftY = -56,
                            RightX = 29,
                            RightY = -128
                        },
                        new
                        {
                            Id = 48,
                            LeftX = -5,
                            LeftY = -33,
                            RightX = 79,
                            RightY = -77
                        },
                        new
                        {
                            Id = 49,
                            LeftX = 61,
                            LeftY = 56,
                            RightX = 92,
                            RightY = -23
                        },
                        new
                        {
                            Id = 50,
                            LeftX = -13,
                            LeftY = 83,
                            RightX = -5,
                            RightY = 65
                        },
                        new
                        {
                            Id = 51,
                            LeftX = 81,
                            LeftY = 17,
                            RightX = 93,
                            RightY = -34
                        },
                        new
                        {
                            Id = 52,
                            LeftX = -27,
                            LeftY = -9,
                            RightX = -11,
                            RightY = -104
                        },
                        new
                        {
                            Id = 53,
                            LeftX = -78,
                            LeftY = 48,
                            RightX = -10,
                            RightY = -36
                        },
                        new
                        {
                            Id = 54,
                            LeftX = 28,
                            LeftY = 46,
                            RightX = 70,
                            RightY = 32
                        },
                        new
                        {
                            Id = 55,
                            LeftX = -13,
                            LeftY = -11,
                            RightX = 28,
                            RightY = -102
                        },
                        new
                        {
                            Id = 56,
                            LeftX = 41,
                            LeftY = 68,
                            RightX = 99,
                            RightY = 17
                        },
                        new
                        {
                            Id = 57,
                            LeftX = -3,
                            LeftY = 43,
                            RightX = 91,
                            RightY = -52
                        },
                        new
                        {
                            Id = 58,
                            LeftX = -38,
                            LeftY = 22,
                            RightX = -24,
                            RightY = -47
                        },
                        new
                        {
                            Id = 59,
                            LeftX = 97,
                            LeftY = -92,
                            RightX = 135,
                            RightY = -150
                        },
                        new
                        {
                            Id = 60,
                            LeftX = 75,
                            LeftY = -42,
                            RightX = 147,
                            RightY = -60
                        },
                        new
                        {
                            Id = 61,
                            LeftX = 43,
                            LeftY = -48,
                            RightX = 59,
                            RightY = -69
                        },
                        new
                        {
                            Id = 62,
                            LeftX = -13,
                            LeftY = 84,
                            RightX = 50,
                            RightY = -13
                        },
                        new
                        {
                            Id = 63,
                            LeftX = 52,
                            LeftY = 10,
                            RightX = 147,
                            RightY = -50
                        },
                        new
                        {
                            Id = 64,
                            LeftX = 81,
                            LeftY = 97,
                            RightX = 108,
                            RightY = 35
                        },
                        new
                        {
                            Id = 65,
                            LeftX = -100,
                            LeftY = 22,
                            RightX = -56,
                            RightY = -43
                        },
                        new
                        {
                            Id = 66,
                            LeftX = 33,
                            LeftY = -25,
                            RightX = 58,
                            RightY = -38
                        },
                        new
                        {
                            Id = 67,
                            LeftX = -35,
                            LeftY = -4,
                            RightX = 20,
                            RightY = -15
                        },
                        new
                        {
                            Id = 68,
                            LeftX = 51,
                            LeftY = -71,
                            RightX = 128,
                            RightY = -137
                        },
                        new
                        {
                            Id = 69,
                            LeftX = -25,
                            LeftY = -29,
                            RightX = 0,
                            RightY = -101
                        },
                        new
                        {
                            Id = 70,
                            LeftX = 43,
                            LeftY = -35,
                            RightX = 109,
                            RightY = -85
                        },
                        new
                        {
                            Id = 71,
                            LeftX = -52,
                            LeftY = 86,
                            RightX = -51,
                            RightY = -6
                        },
                        new
                        {
                            Id = 72,
                            LeftX = 19,
                            LeftY = -78,
                            RightX = 118,
                            RightY = -148
                        },
                        new
                        {
                            Id = 73,
                            LeftX = 14,
                            LeftY = 43,
                            RightX = 67,
                            RightY = 10
                        },
                        new
                        {
                            Id = 74,
                            LeftX = 20,
                            LeftY = -2,
                            RightX = 23,
                            RightY = -100
                        },
                        new
                        {
                            Id = 75,
                            LeftX = -62,
                            LeftY = 6,
                            RightX = -17,
                            RightY = -90
                        },
                        new
                        {
                            Id = 76,
                            LeftX = -30,
                            LeftY = 43,
                            RightX = 59,
                            RightY = 10
                        },
                        new
                        {
                            Id = 77,
                            LeftX = -90,
                            LeftY = -4,
                            RightX = -19,
                            RightY = -33
                        },
                        new
                        {
                            Id = 78,
                            LeftX = -95,
                            LeftY = 16,
                            RightX = -87,
                            RightY = -80
                        },
                        new
                        {
                            Id = 79,
                            LeftX = -69,
                            LeftY = -3,
                            RightX = -43,
                            RightY = -88
                        },
                        new
                        {
                            Id = 80,
                            LeftX = -67,
                            LeftY = -29,
                            RightX = -36,
                            RightY = -84
                        },
                        new
                        {
                            Id = 81,
                            LeftX = 90,
                            LeftY = 5,
                            RightX = 123,
                            RightY = -57
                        },
                        new
                        {
                            Id = 82,
                            LeftX = 40,
                            LeftY = 35,
                            RightX = 91,
                            RightY = 32
                        },
                        new
                        {
                            Id = 83,
                            LeftX = -5,
                            LeftY = -1,
                            RightX = 32,
                            RightY = -9
                        },
                        new
                        {
                            Id = 84,
                            LeftX = 71,
                            LeftY = -39,
                            RightX = 132,
                            RightY = -52
                        },
                        new
                        {
                            Id = 85,
                            LeftX = 2,
                            LeftY = 90,
                            RightX = 4,
                            RightY = -1
                        },
                        new
                        {
                            Id = 86,
                            LeftX = -82,
                            LeftY = 70,
                            RightX = -50,
                            RightY = 11
                        },
                        new
                        {
                            Id = 87,
                            LeftX = 17,
                            LeftY = -52,
                            RightX = 88,
                            RightY = -68
                        },
                        new
                        {
                            Id = 88,
                            LeftX = -45,
                            LeftY = -19,
                            RightX = 37,
                            RightY = -56
                        },
                        new
                        {
                            Id = 89,
                            LeftX = -16,
                            LeftY = -48,
                            RightX = 64,
                            RightY = -99
                        },
                        new
                        {
                            Id = 90,
                            LeftX = 59,
                            LeftY = 41,
                            RightX = 100,
                            RightY = 31
                        },
                        new
                        {
                            Id = 91,
                            LeftX = -40,
                            LeftY = -5,
                            RightX = -21,
                            RightY = -27
                        },
                        new
                        {
                            Id = 92,
                            LeftX = -51,
                            LeftY = 62,
                            RightX = 20,
                            RightY = -19
                        },
                        new
                        {
                            Id = 93,
                            LeftX = 39,
                            LeftY = 34,
                            RightX = 117,
                            RightY = -49
                        },
                        new
                        {
                            Id = 94,
                            LeftX = -78,
                            LeftY = 17,
                            RightX = -24,
                            RightY = -28
                        },
                        new
                        {
                            Id = 95,
                            LeftX = 46,
                            LeftY = -25,
                            RightX = 66,
                            RightY = -55
                        },
                        new
                        {
                            Id = 96,
                            LeftX = -59,
                            LeftY = 72,
                            RightX = 23,
                            RightY = -26
                        },
                        new
                        {
                            Id = 97,
                            LeftX = 7,
                            LeftY = -25,
                            RightX = 55,
                            RightY = -72
                        },
                        new
                        {
                            Id = 98,
                            LeftX = -27,
                            LeftY = -77,
                            RightX = 30,
                            RightY = -81
                        },
                        new
                        {
                            Id = 99,
                            LeftX = 24,
                            LeftY = -94,
                            RightX = 43,
                            RightY = -167
                        },
                        new
                        {
                            Id = 100,
                            LeftX = -60,
                            LeftY = 7,
                            RightX = 36,
                            RightY = -88
                        },
                        new
                        {
                            Id = 101,
                            LeftX = 97,
                            LeftY = 57,
                            RightX = 121,
                            RightY = 35
                        },
                        new
                        {
                            Id = 102,
                            LeftX = 92,
                            LeftY = 43,
                            RightX = 97,
                            RightY = -31
                        },
                        new
                        {
                            Id = 103,
                            LeftX = 61,
                            LeftY = -95,
                            RightX = 146,
                            RightY = -108
                        },
                        new
                        {
                            Id = 104,
                            LeftX = -90,
                            LeftY = -47,
                            RightX = -33,
                            RightY = -67
                        },
                        new
                        {
                            Id = 105,
                            LeftX = 34,
                            LeftY = 60,
                            RightX = 92,
                            RightY = -10
                        },
                        new
                        {
                            Id = 106,
                            LeftX = -8,
                            LeftY = 9,
                            RightX = 70,
                            RightY = -63
                        },
                        new
                        {
                            Id = 107,
                            LeftX = -53,
                            LeftY = -69,
                            RightX = 15,
                            RightY = -126
                        },
                        new
                        {
                            Id = 108,
                            LeftX = -69,
                            LeftY = 85,
                            RightX = -17,
                            RightY = 24
                        },
                        new
                        {
                            Id = 109,
                            LeftX = -82,
                            LeftY = -69,
                            RightX = -74,
                            RightY = -116
                        },
                        new
                        {
                            Id = 110,
                            LeftX = -74,
                            LeftY = 57,
                            RightX = -42,
                            RightY = 53
                        },
                        new
                        {
                            Id = 111,
                            LeftX = -81,
                            LeftY = 37,
                            RightX = 13,
                            RightY = -53
                        },
                        new
                        {
                            Id = 112,
                            LeftX = -6,
                            LeftY = -12,
                            RightX = 85,
                            RightY = -18
                        },
                        new
                        {
                            Id = 113,
                            LeftX = 51,
                            LeftY = -94,
                            RightX = 94,
                            RightY = -188
                        },
                        new
                        {
                            Id = 114,
                            LeftX = 15,
                            LeftY = 77,
                            RightX = 114,
                            RightY = 34
                        },
                        new
                        {
                            Id = 115,
                            LeftX = -4,
                            LeftY = 57,
                            RightX = 11,
                            RightY = 13
                        },
                        new
                        {
                            Id = 116,
                            LeftX = 14,
                            LeftY = 8,
                            RightX = 60,
                            RightY = 1
                        },
                        new
                        {
                            Id = 117,
                            LeftX = 5,
                            LeftY = -37,
                            RightX = 13,
                            RightY = -136
                        },
                        new
                        {
                            Id = 118,
                            LeftX = 18,
                            LeftY = 89,
                            RightX = 37,
                            RightY = 34
                        },
                        new
                        {
                            Id = 119,
                            LeftX = 19,
                            LeftY = -26,
                            RightX = 56,
                            RightY = -121
                        },
                        new
                        {
                            Id = 120,
                            LeftX = 59,
                            LeftY = 46,
                            RightX = 135,
                            RightY = 6
                        },
                        new
                        {
                            Id = 121,
                            LeftX = 49,
                            LeftY = 45,
                            RightX = 53,
                            RightY = 24
                        },
                        new
                        {
                            Id = 122,
                            LeftX = -2,
                            LeftY = -73,
                            RightX = 46,
                            RightY = -76
                        },
                        new
                        {
                            Id = 123,
                            LeftX = 43,
                            LeftY = 38,
                            RightX = 49,
                            RightY = 3
                        },
                        new
                        {
                            Id = 124,
                            LeftX = 62,
                            LeftY = 51,
                            RightX = 114,
                            RightY = 21
                        },
                        new
                        {
                            Id = 125,
                            LeftX = 1,
                            LeftY = 32,
                            RightX = 59,
                            RightY = -67
                        },
                        new
                        {
                            Id = 126,
                            LeftX = 70,
                            LeftY = 78,
                            RightX = 72,
                            RightY = 15
                        },
                        new
                        {
                            Id = 127,
                            LeftX = 5,
                            LeftY = -78,
                            RightX = 10,
                            RightY = -172
                        },
                        new
                        {
                            Id = 128,
                            LeftX = -57,
                            LeftY = 69,
                            RightX = 21,
                            RightY = -30
                        },
                        new
                        {
                            Id = 129,
                            LeftX = -6,
                            LeftY = 41,
                            RightX = 36,
                            RightY = 0
                        },
                        new
                        {
                            Id = 130,
                            LeftX = -100,
                            LeftY = 6,
                            RightX = -60,
                            RightY = 4
                        },
                        new
                        {
                            Id = 131,
                            LeftX = -85,
                            LeftY = 81,
                            RightX = 11,
                            RightY = 73
                        },
                        new
                        {
                            Id = 132,
                            LeftX = 97,
                            LeftY = -69,
                            RightX = 133,
                            RightY = -78
                        },
                        new
                        {
                            Id = 133,
                            LeftX = 84,
                            LeftY = -100,
                            RightX = 99,
                            RightY = -183
                        },
                        new
                        {
                            Id = 134,
                            LeftX = -83,
                            LeftY = -12,
                            RightX = 1,
                            RightY = -51
                        },
                        new
                        {
                            Id = 135,
                            LeftX = -79,
                            LeftY = 75,
                            RightX = -51,
                            RightY = -2
                        },
                        new
                        {
                            Id = 136,
                            LeftX = 30,
                            LeftY = -11,
                            RightX = 39,
                            RightY = -39
                        },
                        new
                        {
                            Id = 137,
                            LeftX = 29,
                            LeftY = -80,
                            RightX = 38,
                            RightY = -134
                        },
                        new
                        {
                            Id = 138,
                            LeftX = -3,
                            LeftY = -58,
                            RightX = 48,
                            RightY = -147
                        },
                        new
                        {
                            Id = 139,
                            LeftX = 18,
                            LeftY = -32,
                            RightX = 87,
                            RightY = -116
                        },
                        new
                        {
                            Id = 140,
                            LeftX = 52,
                            LeftY = -23,
                            RightX = 68,
                            RightY = -101
                        },
                        new
                        {
                            Id = 141,
                            LeftX = -80,
                            LeftY = -18,
                            RightX = -75,
                            RightY = -91
                        },
                        new
                        {
                            Id = 142,
                            LeftX = -80,
                            LeftY = 43,
                            RightX = -37,
                            RightY = 16
                        },
                        new
                        {
                            Id = 143,
                            LeftX = 65,
                            LeftY = -59,
                            RightX = 105,
                            RightY = -132
                        },
                        new
                        {
                            Id = 144,
                            LeftX = -29,
                            LeftY = 29,
                            RightX = -4,
                            RightY = 26
                        },
                        new
                        {
                            Id = 145,
                            LeftX = 32,
                            LeftY = -42,
                            RightX = 52,
                            RightY = -140
                        },
                        new
                        {
                            Id = 146,
                            LeftX = 13,
                            LeftY = 69,
                            RightX = 101,
                            RightY = 32
                        },
                        new
                        {
                            Id = 147,
                            LeftX = -17,
                            LeftY = 72,
                            RightX = 6,
                            RightY = 32
                        },
                        new
                        {
                            Id = 148,
                            LeftX = 75,
                            LeftY = 32,
                            RightX = 82,
                            RightY = -59
                        },
                        new
                        {
                            Id = 149,
                            LeftX = 27,
                            LeftY = 26,
                            RightX = 104,
                            RightY = -32
                        },
                        new
                        {
                            Id = 150,
                            LeftX = -14,
                            LeftY = -12,
                            RightX = 78,
                            RightY = -101
                        },
                        new
                        {
                            Id = 151,
                            LeftX = 51,
                            LeftY = -60,
                            RightX = 125,
                            RightY = -103
                        },
                        new
                        {
                            Id = 152,
                            LeftX = -85,
                            LeftY = 69,
                            RightX = -13,
                            RightY = 9
                        },
                        new
                        {
                            Id = 153,
                            LeftX = 17,
                            LeftY = -13,
                            RightX = 24,
                            RightY = -54
                        },
                        new
                        {
                            Id = 154,
                            LeftX = -68,
                            LeftY = 36,
                            RightX = 21,
                            RightY = 16
                        },
                        new
                        {
                            Id = 155,
                            LeftX = 80,
                            LeftY = -26,
                            RightX = 90,
                            RightY = -96
                        },
                        new
                        {
                            Id = 156,
                            LeftX = -34,
                            LeftY = 35,
                            RightX = -22,
                            RightY = -3
                        },
                        new
                        {
                            Id = 157,
                            LeftX = 42,
                            LeftY = -96,
                            RightX = 44,
                            RightY = -168
                        },
                        new
                        {
                            Id = 158,
                            LeftX = -57,
                            LeftY = -27,
                            RightX = 3,
                            RightY = -100
                        },
                        new
                        {
                            Id = 159,
                            LeftX = 58,
                            LeftY = 47,
                            RightX = 68,
                            RightY = -11
                        },
                        new
                        {
                            Id = 160,
                            LeftX = -94,
                            LeftY = 52,
                            RightX = -19,
                            RightY = -45
                        },
                        new
                        {
                            Id = 161,
                            LeftX = -84,
                            LeftY = 97,
                            RightX = -13,
                            RightY = 39
                        },
                        new
                        {
                            Id = 162,
                            LeftX = -81,
                            LeftY = -67,
                            RightX = 18,
                            RightY = -123
                        },
                        new
                        {
                            Id = 163,
                            LeftX = -27,
                            LeftY = 63,
                            RightX = -26,
                            RightY = 48
                        },
                        new
                        {
                            Id = 164,
                            LeftX = -97,
                            LeftY = -76,
                            RightX = -13,
                            RightY = -90
                        },
                        new
                        {
                            Id = 165,
                            LeftX = 79,
                            LeftY = 0,
                            RightX = 127,
                            RightY = -5
                        },
                        new
                        {
                            Id = 166,
                            LeftX = -86,
                            LeftY = 4,
                            RightX = -9,
                            RightY = -41
                        },
                        new
                        {
                            Id = 167,
                            LeftX = -8,
                            LeftY = -33,
                            RightX = 76,
                            RightY = -114
                        },
                        new
                        {
                            Id = 168,
                            LeftX = 34,
                            LeftY = 97,
                            RightX = 35,
                            RightY = 81
                        },
                        new
                        {
                            Id = 169,
                            LeftX = 34,
                            LeftY = 83,
                            RightX = 95,
                            RightY = 28
                        },
                        new
                        {
                            Id = 170,
                            LeftX = 18,
                            LeftY = -8,
                            RightX = 61,
                            RightY = -62
                        },
                        new
                        {
                            Id = 171,
                            LeftX = 49,
                            LeftY = -49,
                            RightX = 96,
                            RightY = -146
                        },
                        new
                        {
                            Id = 172,
                            LeftX = -83,
                            LeftY = -59,
                            RightX = -31,
                            RightY = -92
                        },
                        new
                        {
                            Id = 173,
                            LeftX = 59,
                            LeftY = 71,
                            RightX = 127,
                            RightY = -19
                        },
                        new
                        {
                            Id = 174,
                            LeftX = -37,
                            LeftY = 93,
                            RightX = -7,
                            RightY = 77
                        },
                        new
                        {
                            Id = 175,
                            LeftX = -68,
                            LeftY = -48,
                            RightX = 18,
                            RightY = -137
                        },
                        new
                        {
                            Id = 176,
                            LeftX = 99,
                            LeftY = 53,
                            RightX = 195,
                            RightY = -11
                        },
                        new
                        {
                            Id = 177,
                            LeftX = -66,
                            LeftY = 9,
                            RightX = 18,
                            RightY = -8
                        },
                        new
                        {
                            Id = 178,
                            LeftX = 65,
                            LeftY = -66,
                            RightX = 83,
                            RightY = -68
                        },
                        new
                        {
                            Id = 179,
                            LeftX = 45,
                            LeftY = -96,
                            RightX = 96,
                            RightY = -138
                        },
                        new
                        {
                            Id = 180,
                            LeftX = 0,
                            LeftY = -35,
                            RightX = 79,
                            RightY = -130
                        },
                        new
                        {
                            Id = 181,
                            LeftX = -91,
                            LeftY = -59,
                            RightX = 0,
                            RightY = -93
                        },
                        new
                        {
                            Id = 182,
                            LeftX = 25,
                            LeftY = 5,
                            RightX = 69,
                            RightY = -20
                        },
                        new
                        {
                            Id = 183,
                            LeftX = 42,
                            LeftY = 48,
                            RightX = 88,
                            RightY = 17
                        },
                        new
                        {
                            Id = 184,
                            LeftX = 1,
                            LeftY = 21,
                            RightX = 58,
                            RightY = -76
                        },
                        new
                        {
                            Id = 185,
                            LeftX = 83,
                            LeftY = -27,
                            RightX = 156,
                            RightY = -73
                        },
                        new
                        {
                            Id = 186,
                            LeftX = -42,
                            LeftY = -88,
                            RightX = 43,
                            RightY = -161
                        },
                        new
                        {
                            Id = 187,
                            LeftX = 49,
                            LeftY = -79,
                            RightX = 52,
                            RightY = -151
                        },
                        new
                        {
                            Id = 188,
                            LeftX = 91,
                            LeftY = 98,
                            RightX = 172,
                            RightY = 94
                        },
                        new
                        {
                            Id = 189,
                            LeftX = 8,
                            LeftY = -78,
                            RightX = 58,
                            RightY = -121
                        },
                        new
                        {
                            Id = 190,
                            LeftX = -66,
                            LeftY = 81,
                            RightX = -23,
                            RightY = -13
                        },
                        new
                        {
                            Id = 191,
                            LeftX = 15,
                            LeftY = 94,
                            RightX = 34,
                            RightY = 51
                        },
                        new
                        {
                            Id = 192,
                            LeftX = -98,
                            LeftY = 36,
                            RightX = -36,
                            RightY = 21
                        },
                        new
                        {
                            Id = 193,
                            LeftX = -22,
                            LeftY = 6,
                            RightX = -9,
                            RightY = -58
                        },
                        new
                        {
                            Id = 194,
                            LeftX = 52,
                            LeftY = 41,
                            RightX = 65,
                            RightY = 8
                        },
                        new
                        {
                            Id = 195,
                            LeftX = -26,
                            LeftY = -19,
                            RightX = 15,
                            RightY = -33
                        },
                        new
                        {
                            Id = 196,
                            LeftX = -66,
                            LeftY = -68,
                            RightX = 33,
                            RightY = -103
                        },
                        new
                        {
                            Id = 197,
                            LeftX = -62,
                            LeftY = -96,
                            RightX = -54,
                            RightY = -151
                        },
                        new
                        {
                            Id = 198,
                            LeftX = 64,
                            LeftY = 12,
                            RightX = 84,
                            RightY = -45
                        },
                        new
                        {
                            Id = 199,
                            LeftX = 53,
                            LeftY = -41,
                            RightX = 100,
                            RightY = -137
                        },
                        new
                        {
                            Id = 200,
                            LeftX = 27,
                            LeftY = -27,
                            RightX = 112,
                            RightY = -67
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
